// Generated by CoffeeScript 1.4.0

/*
#
# A general event object, e.g. for passing to handlers.
# Useful for event logic, passing to handlers to expose behaviors
# like preventing defaults, etc.
# 
# Where appropriate, modelled after the W3C DOM Event interface.
# @see http://www.w3.org/TR/DOM-Level-3-Events/
# @see https://developer.mozilla.org/en-US/docs/DOM/event
#
*/


(function() {
  var AbstractEvent;

  AbstractEvent = (function() {

    function AbstractEvent(options) {
      this.type = options.type;
      this.timeStamp = new Date();
      this.defaultPrevented = false;
    }

    AbstractEvent.prototype.preventDefault = function() {
      return this.defaultPrevented = true;
    };

    return AbstractEvent;

  })();

  module.exports = AbstractEvent;

}).call(this);
